### ISSUE TITLE
otto with JavascriptInterface in api < 17

### ISSUE THREAD

**Issue by maxwell-nc** [square/otto#196] opened 2016-11-14 09:58 UTC
java.lang.ClassNotFoundException
android.webkit.JavascriptInterface
java.lang.NoClassDefFoundError:android/webkit/JavascriptInterface
java.lang.reflect.Method.isAnnotationPresent(Native Method)
......
Caused by:
java.lang.ClassNotFoundException:android.webkit.JavascriptInterface
dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
java.lang.ClassLoader.loadClass(ClassLoader.java:501)
java.lang.ClassLoader.loadClass(ClassLoader.java:461)
java.lang.reflect.Method.isAnnotationPresent(Native Method)
java.lang.reflect.Method.isAnnotationPresent(Method.java:284)
com.squareup.otto.AnnotatedHandlerFinder.loadAnnotatedMethods(AnnotatedHandlerFinder.java:72)
com.squareup.otto.AnnotatedHandlerFinder.loadAnnotatedProducerMethods(AnnotatedHandlerFinder.java:49)
com.squareup.otto.AnnotatedHandlerFinder.findAllProducers(AnnotatedHandlerFinder.java:140)
com.squareup.otto.HandlerFinder$1.findAllProducers(HandlerFinder.java:33)
com.squareup.otto.Bus.register(Bus.java:190)

**Comment by JakeWharton** [comment] 2016-11-14 23:26
This seems like a duplicate of #139.

**Closed as completed by JakeWharton** 2016-11-14 23:26 UTC
